# ThemeKit Configuration (config.yml)
#
# QUICK SETUP INSTRUCTIONS:
# 1. Replace YOUR_PASSWORD with your Shopify API password/access token
# 2. Replace your-store.myshopify.com with your actual store URL
# 3. Replace 123456789 with your actual theme ID (DO NOT use "live" as it's no longer supported)
#
# To find your theme ID:
# - Go to your Shopify admin
# - Navigate to Online Store > Themes
# - Find your theme and click "Customize"
# - Check the URL in your browser - it will contain theme_id=123456789

development:
  password: "test"
  theme_id: "live" # Replace with your actual theme ID, "live" is no longer supported
  store: staging-curalife.myshopify.com
  ignore_files:
    - "*.git*"
    - "*.md"
    - "node_modules/*"
    - "shopify-dev*.js"
    - "vite-*.js"
    - "vite.config.js"
    - "config.yml"
