# Shopify Theme Configuration File
# This file is required for Shopify CLI to recognize this directory as a theme

[environments.development]
theme_directory = "."
ignored_paths = [
  "node_modules/**",
  ".git/**",
  ".github/**",
  ".vscode/**",
  "*.md",
  "*.txt"
]