# This file contains theme configuration for the Shopify CLI.
# It helps Shopify recognize this directory as a valid theme.
# Learn more: https://shopify.dev/docs/themes/tools/cli

[environments]
development = { theme_directory = "./", ignored_paths = ["node_modules", ".git", ".github", ".vscode"] }